name: This will run first Yaml Pipeline
on:
    pull_request:
        branches:
            - masteer
        types:
            [closed]
jobs:
    testing:
        name: 🎉 Testing
        runs-on: ubuntu-latest
        steps:
            - name: Testing phase
              uses: echo "justin"
    deploy:
        name: 🎉 Deploy
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Deployment phase
            - uses: echo "Hello"
              
