name: This will run first Yaml Pipeline
on:
    pull_request:
        branches:
            - master
        types:
            [closed]
jobs:
    testing:
        name: 🎉 Testing
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Testing phase
              run: echo "justin"
    deploy:
        name: 🎉 Deploy
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: linux command will run
              run: echo "Your name"
