name: This will run first Yaml Pipeline
on:
    pull_request:
        branches:
            - master
        types:
            [closed]
jobs:
    testing:
        name: 🎉 Deploy
        runs-on: ubuntu-latest
        steps:
            - name: Will get latest code
              uses: actions/checkout@v2
            - name: linux command will run
              run: 
                echo "Your name"
